### ISSUE TITLE
Resizing of text not working properly. 

### ISSUE THREAD

**Issue by timvanuum** [Fuzzyma/svg.resize.js#11]
It seems that the resizing of text doens't work well. It jump directly to a large font size. Also it does't pin the edge to the mouse pointer but jumps off and end up resizing while the mouse is inside the selection.

**Comment by Fuzzyma** [comment]
I am not sure what you are trying to do. Resizing Text? That's nothing this
plugin is supposed to to :D.
However that would be an interesting thing

Tim van Uum <notifications@github.com> schrieb am Mi., 17.02.2016, 13:40:

**Comment by timvanuum** [comment]
Oh, didn't knew that. But it's kind of working already. The resizing part is already working on svg text objects, it just jumps to a large font size when you start to resize. I'll look a bit into it, but I'm not a pro at this plugin (svg.js) or plain javascript / prototyping in general. 

Else I'll use a dropdown font-size selector.

**Comment by Fuzzyma** [comment]
I would say a drop down is what the user sees normally. The thing you
resize when working with text is the text box and not the font size.

It's doing something because the size function I use is misused as font
size when called on a text element. So it tries to alter the box but
instead the fontsize is changed. Thats why it jumps to this big font size

Tim van Uum <notifications@github.com> schrieb am Mi., 17.02.2016, 14:02:

**Comment by diruuu** [comment]
Thanks for the awesome plugin,
could you also make it work on text box? The only problem now is that it jumps directly to a large font size every time it resized, anything else's fine, the rotation also works fine. I thought if will be great if we also could directly change the font-size with the select plugin. 

Thanks!

**Comment by diruuu** [comment]
I got time to look at your code and made a few changes. I've made a pull request.

**Comment by Fuzzyma** [comment]
closed with 1.1.1

**Comment by kirvinod** [comment]
Hi, I still getting an issue with this. 

draw.text("Double click to edit").move(200,200).selectize().resize();


soon I hold resize point it jumps to the top corner as in the image below.

![Untitled](https://user-images.githubusercontent.com/20281787/54873164-c1b25a80-4dc8-11e9-965b-680b8b6c0a7d.gif)
