### ISSUE TITLE
Version Query

### ISSUE THREAD

**Issue by JohnHardy** [Fuzzyma/svg.resize.js#15]
Hey!  Great library!

I am trying to use it in conjunction with http://jillix.github.io/svg.pan-zoom.js/ but the download on your main page is built against an older 1x version, and the one in master gives me the following:

```
TypeError: svg.polygon(...).select is not a function 
```
when used with the latest release of SVG.js (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.3.0/svg.min.js)

Please could you point me in the direction of the right library version you used to build against so I can track back through `svg.pan-zoom.js` until I get a working version!

Cheers!

**Comment by Fuzzyma** [comment]
From the doc of svg.select.js:
>Note: Duo to naming conflicts the exported method was renamed from select() to selectize().

Also the package.json / bower.json correctly states svg.js v2.2.5 as dependency

**Comment by JohnHardy** [comment]
Thanks, much appreciated!
