### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by dhardtke** [Fuzzyma/svg.resize.js#2]
Hey Fuzzyma,

thanks for your awesome plugin.

Is there a possibility that you might add event or callback support?

An option to specify a callback that fires whenever we a resizing a shape or the resize was done would be amazing.

**Comment by Fuzzyma** [comment]
Good idea. I will add that when I am back home (at Monday ;)  )

**Comment by dhardtke** [comment]
You know what also would be awesome: Being able to remove the resize ability later on.
I found no way to do it right now.

Thanks for your efforts. You're doing an amazing job!

**Comment by Fuzzyma** [comment]
With svg.resize.js I reworked all of my 3 addons now.
It fires an event `resizedone` when resizing is done (obvisouly).
Furthermore you can call `rect.resize('stop')` to disable the resize-function.

Sidetip: You can enable snap to grid while resizing. You just have to call resize with other parameters (e.g. on ctrl down and up - see demo for this)

**Comment by dhardtke** [comment]
This is brilliant!

**Comment by cactis** [comment]
I try to bind click event to toggle an icon's resizable mode,
but it dosen't work.

```
icon.click ->
      if this.selected
        # this.selectize().resize('stop')
        # this.selectize().stop()
        this.resize 'stop'
        # icon.resize('stop')
        # icon.selectize().resize 'stop'
        # this.done()
        this.selected = undefined
      else
        this.selectize().resize()
          # resizedone: ->
        this.selected = true
```
thanks

**Comment by Fuzzyma** [comment]
Any reason why you wrote that here? That's a closed issue. 
However: there is no point in toggling the resizing because a shape can only be resized when it's selected. That's why you simply can't disable resizing. You can only disable the selection

**Comment by cactis** [comment]
sorry.  
My question is any usage sample for "resizedone"?
I want to deselect the icon when it's resized done.


yes, it's work!  Thanks!
```
icon.selectize(false)
```

**Comment by Fuzzyma** [comment]
```javascript
icon.on('resizedone', function() {
    this.selectize(false)
} 
```

**Comment by Fuzzyma** [comment]
Because it's an event and no method and click is only a shortcut to add click handlers to elements 

#rtfm
