### ISSUE TITLE
Resizing with Aspect Ratio

### ISSUE THREAD

**Issue by Santhoshsvg** [Fuzzyma/svg.resize.js#21]
Correct me if i am wrong.

Somewhere while using the older version and the newer version of svg resize, i came across using the Shift key for maintaining the Aspect ratio.

Now in the latest svg.resize there is no information regarding the maintaining Aspect ratio and resizing.

Please throw some light on this.

**Comment by Fuzzyma** [comment]
It never was there - shift key is for snapping to a grid which you can specify with an option

**Comment by Santhoshsvg** [comment]
Thanks a lot Ulrich master.

Will look for options and will try to use the PreserveAspectRatio property if possbile.

Will close this comment.
