### ISSUE TITLE
resizestart event

### ISSUE THREAD

**Issue by jkevingutierrez** [Fuzzyma/svg.resize.js#22]
Could be possible to add an event when the resize started ?

**Comment by albohlabs** [comment]
Resize begins in [`ResizeHandler.prototype.resize`](https://github.com/Fuzzyma/svg.resize.js/blob/master/src/svg.resize.js#L91) method. So you can easily throw in a `this.el.fire('resizestart')` and create a PR. 😁🐝

**Comment by GuskiS** [comment]
I need this too, but not sure how to do PR because I can't create new branch on this repository. Can someone do this please?

**Comment by GuskiS** [comment]
#25 Created pull request.

**Comment by Fuzzyma** [comment]
PR was merged. Available as `1.4.0`
