### ISSUE TITLE
Save the actual element position and rotation

### ISSUE THREAD

**Issue by ibarral** [Fuzzyma/svg.resize.js#26]
Hello,

I want to save to actual position and rotation of an element.

I'm moving the element over my SVG using the "draggable" plugin, and rotating it using the "resize" plugin.

I have noticed that when a rotation happens, it affects the "transform matrix" prop of the element. I don't know if there is an option to make it work with the "transform rotate" prop, I think would be easier).

Anyway, what are the actual values that I have to save, and the get again, to replicate the element position and rotation?

Thanks!

**Comment by Fuzzyma** [comment]
In svg.js every transformation is merged into a single matrix. That makes live at some points harder but at other points much easier. To get the transformation matrix you can call `transform()` without parameters which gives you the `a-f` values of the matrix together with some extraced plain transformation values such as `rotation, scale, skew, translation`. If you only rotate and never do any other rotation than this, you might use the rotation value. However: To be save and to replicate the transformation, just save the object you get back of `transform()` and apply it to another element with `transform(obj)`.
To replicate the position of the element you would read the x and y attributes of the element or call `x()` and `y()` without parameter to get them.

Hope it helped.
Btw: Stackoverflow is for questions and the issue tracker for issues ;)

**Comment by ibarral** [comment]
Thanks! And I will use Stackoverflow for my questions. Sorry for that ;)

**Comment by Fuzzyma** [comment]
No problem. Glad I could help!
