### ISSUE TITLE
Bug with lines

### ISSUE THREAD

**Issue by dhardtke** [Fuzzyma/svg.resize.js#3]
Hey,

I don't know if it's the resize or the select plugin that causes this issue, but (even with the older version) have the issue that after I am trying to select a Line, I get an "Uncaught TypeError":
![Error](https://cloud.githubusercontent.com/assets/1360135/8045919/440a04a4-0e37-11e5-9e33-a709134f5d7b.PNG)

It happens with and without the "deepSelect" option.

**Comment by Fuzzyma** [comment]
My fault. I wrote something like `[value1.x] - value2.x` instead of `[value1.x - value2.x]`.
It was a mistake in svg.select.js which is fixed in `1.0.1`

**Comment by dhardtke** [comment]
Yep, seems to be fixed +1

**Comment by dhardtke** [comment]
But there seems to be a different, new issue:
The handlers for resizing seem to disappear when using deepSelect: true when I resize the line so it is horizontal:
http://puu.sh/iwbGd/646dbe0832.png (before)
http://puu.sh/iwbKO/0a2306ff4a.png (after)

**Comment by Fuzzyma** [comment]
Your code please ;)

**Comment by dhardtke** [comment]
There you go: https://jsfiddle.net/bb3m5w8e/

**Comment by Fuzzyma** [comment]
Fixed in 1.0.2 - still an svg.select.js - issue ;)
