### ISSUE TITLE
Resize in mobile

### ISSUE THREAD

**Issue by satrun77** [Fuzzyma/svg.resize.js#7]
Thanks for great plugin. I was wondering is it possible to use resize in mobile with touch events?

**Comment by Fuzzyma** [comment]
I had no intention to implement that but I think it should be possible.
I am short on time at the moment. So if you want to create a PR for that, I would really appreciate that.

**Comment by rui-cruz** [comment]
Any news on TouchEvents?

**Comment by Fuzzyma** [comment]
No news till now. There is so much stuff to do...
